import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { Header } from '@/src/components/shared/Header'
import { Footer } from '@/src/components/shared/Footer'
import '@/src/sass/globals.sass'

const rubik = Rubik({ weight: ['400', '500', '600', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Future Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
