import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { Header } from 'app/components/shared/Header'
import { Footer } from 'app/components/shared/Footer'
import './globals.css'

const rubik = Rubik({ weight: ['300', '400', '500', '600', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Future Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
